# -*- coding: utf-8 -*-
"""ARCH/GARCH

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GqNycEwXqMlSTRaMA4TsCLXCEyGzxcup
"""

!pip install arch

import pandas as pd
from statsmodels.tsa.stattools import adfuller
from arch.unitroot import PhillipsPerron
from arch import arch_model

df=pd.read_csv("euro.csv") #loading the file

df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y') #converting date column "str" to "datetime" object
df.set_index('Date', inplace=True)

df.head(5) #printing top-5 data on the table

df.info()

df.describe() # prinitng basic Data statistics

df.plot()

"""### Filtering data for range April-2016 till April-2018"""

mmr1= df.loc['2022-1-1':'2023-1-1'] #filtering data for 2022-1-1 till 2023-1-1

mmr1.plot()

"""## Statistical test

### 1. Augmented Dickey-Fuller test
"""

result = adfuller(mmr1) #augmented Dickey-Fuller test
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
print('Critical Values:')
for key, value in result[4].items():
 print('\t%s: %.3f' % (key, value))

"""### 2. Phillips Perron test"""

PhillipsPerron(mmr1)

"""Since ADF test statistic is negative and p-value is higher we cannot reject the null of unit root and PP test is rehecting the null hypothesis, hence data is non-stationary

time series is not stationary and will require differencing to make it stationary, at least a difference order of 1.

### First Difference of mmr1
"""

dmmr1 = mmr1.diff()

dmmr1.iloc[0]=mmr1.iloc[0]

result = adfuller(dmmr1)
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
print('Critical Values:')
for key, value in result[4].items():
 print('\t%s: %.3f' % (key, value))

PhillipsPerron(dmmr1)

"""### After taking first diffrenec the data is stationary"""

from statsmodels.graphics.tsaplots import plot_acf
from matplotlib import pyplot

"""### Plotting Auto-correlation function"""

plot_acf(mmr1,lags=50) #plotting autocorrelation at First Difference 
pyplot.show()

"""We are getting positive auto-correlation at 30th lagsignificant for the first 10 lags.

A good starting point for the AR parameter of the model may be 10
"""

plot_acf(dmmr1,lags=50) #plotting autocorelation of first difference
pyplot.show()

"""### Plotting Partial Auto-Correlation function"""

from statsmodels.graphics.tsaplots import plot_pacf

plot_pacf(mmr1) #partial Autocorrelation of actual series
pyplot.show()

plot_pacf(dmmr1) #Partial Auto-Correlation of First Difference
pyplot.show()

"""Since ACF plot shows that Auto-correlation is dropping immediately after first lag and we can use ARIM

# ARCH Models
"""

from statsmodels.tsa.arima.model import ARIMA #loading ARIMA model in python

model = arch_model(dmmr1, mean='Zero', vol='ARCH', p=10)
model_fit = model.fit() # model fitting 
# summary of fit model
print(model_fit.summary())
# line plot of residuals
residuals = pd.DataFrame(model_fit.resid)
residuals.plot()
pyplot.show()

"""## First period ahead value Forcasting for Feb-2023"""

test = df.loc['2023-1-1':'2023-1-15'][:10]
test.head(10)

forecasts=model_fit.forecast(horizon=1, reindex=False)
print(forecasts.residual_variance.iloc[-3:])

forecasts.residual_variance.iloc[-3:]['h.1'].to_list()[0]

residual_1 = []
residual_2 = []
for i in range(0,10): #Rolling Forecast ARCH model
  mmr1= df.loc['2022-1-1':f'2023-1-{1+i}'] 
  dmmr1 = mmr1.diff()
  dmmr1.iloc[0]=mmr1.iloc[0]
  # # fit model
  model = arch_model(dmmr1, mean='Zero', vol='ARCH', p=5) #-> ARCH model 1
  model_fit = model.fit()
  forecasts1=model_fit.forecast(horizon=1, reindex=False)

  residual_1.append(forecasts1.residual_variance.iloc[-3:]['h.1'].to_list()[0]) #First period ahead forecast for Model1 

  #prediction by model 2
  model2 = arch_model(dmmr1, mean='Zero', vol='ARCH', p=10) #-> ARCH model 2
  model_fit2 = model2.fit()
  forecasts2=model_fit2.forecast(horizon=1, reindex=False)

  residual_2.append(forecasts2.residual_variance.iloc[-3:]['h.1'].to_list()[0]) #First period ahead forecast for Model2

test['Model 1 predicted']=test['EURO']+residual_1
test['Model 2 predicted']=test['EURO']+residual_2

test

from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(test['EURO'],test['Model 1 predicted']) #MSPE for ARCH Model 1

mean_absolute_percentage_error(test['EURO'],test['Model 2 predicted']) #MSPE for ARCH Model 2

!pip install dieboldmariano

"""## Debol Mariano Test"""

from dieboldmariano import dm_test

dm_test(test["EURO"], test['Model 1 predicted'], test['Model 2 predicted'], one_sided=True)

import matplotlib.pyplot as plt
plt.plot(test['EURO'],label="Actual Time Series")
plt.plot(test['Model 1 predicted'], color='red',label="ARCH model 1")
plt.legend()

